spaceship remove user
spaceship remove async

SPACESHIP_USER_SHOW=always
SPACESHIP_PROMPT_ADD_NEWLINE=false
SPACESHIP_CHAR_SYMBOL="❯"
SPACESHIP_CHAR_PREFIX="  "
SPACESHIP_CHAR_SUFFIX=" "
SPACESHIP_EXEC_TIME_PREFIX=""
